#!/system/bin/sh
#If the script does not run, do this "chmod 777 appable.sh" and try again.
echo
echo "###########################################"
echo "ver\t: 161217"
echo "mail\t: metinsanli@gmail.com"
echo "file\t: "$0
echo "###########################################"
echo

pm $1 com.adidas.micoach
pm $1 com.android.backupconfirm
#pm $1 com.android.bluetooth
#pm $1 com.android.browser
pm $1 com.android.browser.res.overlay
pm $1 com.android.calculator2
#pm $1 com.android.calendar
#pm $1 com.android.certinstaller
#pm $1 com.android.defcontainer
#pm $1 com.android.email
pm $1 com.android.exchange
pm $1 com.android.galaxy4
#pm $1 com.android.htmlviewer
#pm $1 com.android.inputdevices
#pm $1 com.android.keychain
#pm $1 com.android.musicfx
#pm $1 com.android.noisefield
#pm $1 com.android.packageinstaller
pm $1 com.android.phasebeam
#pm $1 com.android.phone
#pm $1 com.android.providers.applications
#pm $1 com.android.providers.calendar
#pm $1 com.android.providers.contacts
#pm $1 com.android.providers.downloads
#pm $1 com.android.providers.downloads.ui
#pm $1 com.android.providers.drm
#pm $1 com.android.providers.media
#pm $1 com.android.providers.partnerbookmarks
pm $1 com.android.providers.partnerbookmarks.res.overlay
#pm $1 com.android.providers.settings
pm $1 com.android.providers.settings.res.overlay
#pm $1 com.android.providers.telephony
#pm $1 com.android.providers.userdictionary
pm $1 com.android.remotecontrolservice
#pm $1 com.android.settings
#pm $1 com.android.sharedstoragebackup
#pm $1 com.android.smspush
#pm $1 com.android.soundrecorder
pm $1 com.android.stk
#pm $1 com.android.systemui
#pm $1 com.android.vending
pm $1 com.android.voicedialer
pm $1 com.android.vpndialogs
pm $1 com.android.wallpaper
pm $1 com.android.wallpaper.holospiral
pm $1 com.android.wallpaper.livepicker
pm $1 com.apksoftware.compass
pm $1 com.facebook.katana
pm $1 com.google.android.apps.genie.geniewidget
pm $1 com.google.android.apps.maps
pm $1 com.google.android.apps.plus
pm $1 com.google.android.apps.uploader
#pm $1 com.google.android.backup
pm $1 com.google.android.feedback
pm $1 com.google.android.gm
pm $1 com.google.android.gms
pm $1 com.google.android.googlequicksearchbox
#pm $1 com.google.android.gsf
#pm $1 com.google.android.gsf.login
pm $1 com.google.android.location
pm $1 com.google.android.marvin.talkback
#pm $1 com.google.android.onetimeinitializer
#pm $1 com.google.android.partnersetup
pm $1 com.google.android.street
#pm $1 com.google.android.syncadapters.calendar
#pm $1 com.google.android.syncadapters.contacts
pm $1 com.google.android.talk
pm $1 com.google.android.tts
pm $1 com.google.android.voicesearch
pm $1 com.google.android.youtube
pm $1 com.mobisystems.office
#pm $1 com.sonyericsson.advancedwidget.clock
pm $1 com.sonyericsson.advancedwidget.feedwidget
pm $1 com.sonyericsson.advancedwidget.friends
#pm $1 com.sonyericsson.advancedwidget.music
pm $1 com.sonyericsson.advancedwidget.notewidget
#pm $1 com.sonyericsson.advancedwidget.onoff
pm $1 com.sonyericsson.advancedwidget.photo
pm $1 com.sonyericsson.advancedwidget.recentcalls
pm $1 com.sonyericsson.advancedwidget.updatestatus
#pm $1 com.sonyericsson.advancedwidget.weather2
#pm $1 com.sonyericsson.album
#pm $1 com.sonyericsson.android.bootinfo
#pm $1 com.sonyericsson.android.camera
#pm $1 com.sonyericsson.android.camera3d
#pm $1 com.sonyericsson.android.cdfinfoaccessor
#pm $1 com.sonyericsson.android.contactsimport
#pm $1 com.sonyericsson.android.drm.services
#pm $1 com.sonyericsson.android.locationbasedwifi
#pm $1 com.sonyericsson.android.omacp
pm $1 com.sonyericsson.android.pobox
pm $1 com.sonyericsson.android.pobox.skn.mono
pm $1 com.sonyericsson.android.pobox.skn.pink
pm $1 com.sonyericsson.android.pobox.skn.selector
pm $1 com.sonyericsson.android.pobox.skn.wood
#pm $1 com.sonyericsson.android.semcrilextension
#pm $1 com.sonyericsson.android.servicemenu
pm $1 com.sonyericsson.android.smartsearch
#pm $1 com.sonyericsson.android.socialphonebook
#pm $1 com.sonyericsson.android.wifi
pm $1 com.sonyericsson.androidapp.everchwallpaper
pm $1 com.sonyericsson.androidapp.fbcalendarsync
pm $1 com.sonyericsson.androidapp.fbmusiclike
pm $1 com.sonyericsson.androidapp.fbsetupwizard
pm $1 com.sonyericsson.androidapp.retaildemo
pm $1 com.sonyericsson.androidapp.storefront
pm $1 com.sonyericsson.androidapp.timescapefeedsplugin
#pm $1 com.sonyericsson.androidapp.torchapp
pm $1 com.sonyericsson.androidapp.wallpaper_earth
pm $1 com.sonyericsson.appshare
#pm $1 com.sonyericsson.audioeffectservice
#pm $1 com.sonyericsson.autopoweroffservice
#pm $1 com.sonyericsson.backuprestore
#pm $1 com.sonyericsson.backupservice.memorycardtransport
#pm $1 com.sonyericsson.backupservice.usbstoragetransport
#pm $1 com.sonyericsson.blacktheme
pm $1 com.sonyericsson.blackthemeblueaccent
#pm $1 com.sonyericsson.bluetheme
#pm $1 com.sonyericsson.cameraextension.permission
#pm $1 com.sonyericsson.capabilities
pm $1 com.sonyericsson.capabilities.res.overlay
#pm $1 com.sonyericsson.conversations
pm $1 com.sonyericsson.conversations.res.overlay
pm $1 com.sonyericsson.crashmonitor
#pm $1 com.sonyericsson.credentialmanagerservice
#pm $1 com.sonyericsson.customizedappinstaller
pm $1 com.sonyericsson.customizedsettings
pm $1 com.sonyericsson.customizedsettings.res.overlay
#pm $1 com.sonyericsson.devicemonitor
#pm $1 com.sonyericsson.dlna
#pm $1 com.sonyericsson.dlnahandover
#pm $1 com.sonyericsson.drmdialogs
pm $1 com.sonyericsson.eventstream
pm $1 com.sonyericsson.eventstream.facebookplugin
pm $1 com.sonyericsson.eventstream.twitterplugin
pm $1 com.sonyericsson.eventstream.twitterpostviewer
pm $1 com.sonyericsson.extras.liveware
pm $1 com.sonyericsson.facebook.postview
pm $1 com.sonyericsson.facebook.proxylogin
pm $1 com.sonyericsson.fbmediadiscovery
#pm $1 com.sonyericsson.fmradio
#pm $1 com.sonyericsson.genericinstaller.android
pm $1 com.sonyericsson.greentheme
#pm $1 com.sonyericsson.home
pm $1 com.sonyericsson.idd.agent
#pm $1 com.sonyericsson.illumination.service
pm $1 com.sonyericsson.infiniteview
#pm $1 com.sonyericsson.initialbootsetup
#pm $1 com.sonyericsson.localcontacts
#pm $1 com.sonyericsson.lockscreen.uxpnxt
#pm $1 com.sonyericsson.metadatacleanup
#pm $1 com.sonyericsson.mtp
#pm $1 com.sonyericsson.mtp.extension.backuprestore
#pm $1 com.sonyericsson.mtp.extension.marlin
#pm $1 com.sonyericsson.mtp.extension.update
#pm $1 com.sonyericsson.music
pm $1 com.sonyericsson.music.googlelyricsplugin
pm $1 com.sonyericsson.music.wikipediaplugin
pm $1 com.sonyericsson.music.youtubekaraokeplugin
pm $1 com.sonyericsson.music.youtubeplugin
#pm $1 com.sonyericsson.musicvisualizer
pm $1 com.sonyericsson.notes
#pm $1 com.sonyericsson.oemCryptoReceiver
#pm $1 com.sonyericsson.omadl
pm $1 com.sonyericsson.orangetheme
#pm $1 com.sonyericsson.organizer
#pm $1 com.sonyericsson.photoeditor
pm $1 com.sonyericsson.pinktheme
#pm $1 com.sonyericsson.provider.customization
#pm $1 com.sonyericsson.provider.useragent
#pm $1 com.sonyericsson.provider.voipcalllog
#pm $1 com.sonyericsson.providers.cnap
#pm $1 com.sonyericsson.providers.protectedmedia
#pm $1 com.sonyericsson.psm.sysmonservice
pm $1 com.sonyericsson.purpletheme
pm $1 com.sonyericsson.r2r.client
pm $1 com.sonyericsson.r2r.client.res.overlay
#pm $1 com.sonyericsson.secureclockservice
#pm $1 com.sonyericsson.settings
#pm $1 com.sonyericsson.setupwizard
#pm $1 com.sonyericsson.shutdownanim
#pm $1 com.sonyericsson.simcontacts
#pm $1 com.sonyericsson.simdetection
#pm $1 com.sonyericsson.smartcard
pm $1 com.sonyericsson.socialengine
pm $1 com.sonyericsson.socialengine.plugins.facebook
pm $1 com.sonyericsson.socialengine.plugins.picasa
pm $1 com.sonyericsson.socialpane.friends
#pm $1 com.sonyericsson.soundenhancement
#pm $1 com.sonyericsson.soundlevelalert
#pm $1 com.sonyericsson.startupflagservice
#pm $1 com.sonyericsson.suquashi.soundpicker
#pm $1 com.sonyericsson.swiqimasterreset
#pm $1 com.sonyericsson.tetherentitlementcheck
pm $1 com.sonyericsson.textinput.chinese
#pm $1 com.sonyericsson.textinput.uxp
pm $1 com.sonyericsson.textinput.uxp.platform.res.overlay
#pm $1 com.sonyericsson.thememanager
pm $1 com.sonyericsson.timescape.ui
pm $1 com.sonyericsson.trackid
pm $1 com.sonyericsson.trackid.res.overlay
pm $1 com.sonyericsson.tvlauncher
pm $1 com.sonyericsson.unplugchargerreminder
pm $1 com.sonyericsson.unsupportedheadsetnotifier
pm $1 com.sonyericsson.updatecenter
#pm $1 com.sonyericsson.usbotg
#pm $1 com.sonyericsson.usbux
#pm $1 com.sonyericsson.vendor.backuprestore
#pm $1 com.sonyericsson.verifycertificatesdummyapp.application
#pm $1 com.sonyericsson.verifycertificatesdummyapp.media
#pm $1 com.sonyericsson.verifycertificatesdummyapp.platform
#pm $1 com.sonyericsson.verifycertificatesdummyapp.shared
#pm $1 com.sonyericsson.video
#pm $1 com.sonyericsson.wallpaperpicker
#pm $1 com.sonyericsson.wappush
pm $1 com.sonyericsson.wappush.res.overlay
#pm $1 com.sonyericsson.widgetpicker
pm $1 com.sonymobile.advancedwidget.topcontacts
pm $1 com.sonymobile.android.externalkeyboardjp
pm $1 com.sonymobile.androidapp.walkmate
#pm $1 com.sonymobile.cameraautoupload
#pm $1 com.sonymobile.connectivitycenter
#pm $1 com.sonymobile.datadisclaimer
#pm $1 com.sonymobile.gpssatellitesnotification
pm $1 com.sonymobile.helpapp7
#pm $1 com.sonymobile.musicslideshow
#pm $1 com.sonymobile.photoanalyzer
#pm $1 com.sonymobile.protectedmedia
#pm $1 com.sonymobile.runtimeskinning.picker
pm $1 com.sonymobile.runtimeskinning.skin1
pm $1 com.sonymobile.shareapplication
#pm $1 com.sonymobile.slideshow
pm $1 com.sonymobile.socialengine.plugins.facebook_sharefrwk
pm $1 com.sonymobile.socialengine.plugins.twitter_sharefrwk
#pm $1 com.sonymobile.storagechecker
#pm $1 com.sonymobile.superstamina
pm $1 com.sonymobile.taskswitcher
pm $1 com.sonymobile.twitter.account
pm $1 com.sonymobile.twitter.setupwizard
pm $1 com.sonymobile.xperialink
#pm $1 com.stericsson.atservice
#pm $1 com.stericsson.ril.oem.service
pm $1 com.svox.pico
pm $1 com.trust5.odp
pm $1 com.wsandroid.suite
pm $1 de.arvatomobile.sonyericsson.playnow.android
pm $1 org.microemu.android.se.appello.lp.WisepilotSE