#!/bin/sh
echo
echo "###########################################"
echo "ver\t: 160123"
echo "mail\t: metinsanli@gmail.com"
echo "file\t: "$0
echo
uname -a
echo
echo "###########################################"
echo

pm $1 com.sonyericsson.setupwizard
pm $1 com.adidas.micoach
pm $1 com.android.backupconfirm
pm $1 com.android.chrome
pm $1 com.android.exchange
pm $1 com.android.galaxy4
pm $1 com.android.phasebeam
pm $1 com.android.providers.settings.res.overlay
pm $1 com.android.remotecontrolservice
pm $1 com.android.voicedialer
pm $1 com.android.vpndialogs
pm $1 com.android.wallpaper
pm $1 com.android.wallpaper.holospiral
pm $1 com.android.wallpaper.livepicker
pm $1 com.android.vending
pm $1 com.apksoftware.compass
pm $1 com.facebook.katana
pm $1 com.google.android.gms
pm $1 com.google.android.apps.maps
pm $1 com.google.android.apps.genie.geniewidget
pm $1 com.google.android.apps.plus
pm $1 com.google.android.apps.uploader
pm $1 com.google.android.feedback
pm $1 com.google.android.googlequicksearchbox
pm $1 com.google.android.marvin.talkback
pm $1 com.google.android.street
pm $1 com.google.android.talk
pm $1 com.google.android.tts
pm $1 com.google.android.voicesearch
pm $1 com.android.vending
pm $1 com.google.android.youtube
pm $1 com.mobisystems.office
pm $1 com.sonyericsson.advancedwidget.notewidget
pm $1 com.sonyericsson.advancedwidget.photo
pm $1 com.sonyericsson.advancedwidget.recentcalls
pm $1 com.sonyericsson.advancedwidget.updatestatus
pm $1 com.sonyericsson.android.pobox
pm $1 com.sonyericsson.android.pobox.skn.mono
pm $1 com.sonyericsson.android.pobox.skn.pink
pm $1 com.sonyericsson.android.pobox.skn.selector
pm $1 com.sonyericsson.android.pobox.skn.wood
pm $1 com.sonyericsson.android.smartsearch
pm $1 com.sonyericsson.androidapp.everchwallpaper
pm $1 com.sonyericsson.androidapp.fbcalendarsync
pm $1 com.sonyericsson.androidapp.fbmusiclike
pm $1 com.sonyericsson.androidapp.fbsetupwizard
pm $1 com.sonyericsson.androidapp.retaildemo
pm $1 com.sonyericsson.androidapp.storefront
pm $1 com.sonyericsson.androidapp.timescapefeedsplugin
pm $1 com.sonyericsson.androidapp.wallpaper_earth
pm $1 com.sonyericsson.appshare
pm $1 com.sonyericsson.backuprestore
pm $1 com.sonyericsson.blacktheme
pm $1 com.sonyericsson.blackthemeblueaccent
pm $1 com.sonyericsson.bluetheme
pm $1 com.sonyericsson.capabilities.res.overlay
pm $1 com.sonyericsson.conversations.res.overlay
pm $1 com.sonyericsson.crashmonitor
pm $1 com.sonyericsson.customizedsettings
pm $1 com.sonyericsson.customizedsettings.res.overlay
pm $1 com.sonyericsson.eventstream
pm $1 com.sonyericsson.eventstream.facebookplugin
pm $1 com.sonyericsson.eventstream.twitterplugin
pm $1 com.sonyericsson.eventstream.twitterpostviewer
pm $1 com.sonyericsson.facebook.postview
pm $1 com.sonyericsson.facebook.proxylogin
pm $1 com.sonyericsson.fbmediadiscovery
pm $1 com.sonyericsson.idd.agent
pm $1 com.sonyericsson.infiniteview
pm $1 com.sonyericsson.music.googlelyricsplugin
pm $1 com.sonyericsson.music.wikipediaplugin
pm $1 com.sonyericsson.music.youtubekaraokeplugin
pm $1 com.sonyericsson.music.youtubeplugin
pm $1 com.sonyericsson.notes
pm $1 com.sonyericsson.orangetheme
pm $1 com.sonyericsson.pinktheme
pm $1 com.sonyericsson.purpletheme
pm $1 com.sonyericsson.r2r.client.res.overlay
pm $1 com.sonyericsson.socialengine
pm $1 com.sonyericsson.socialengine.plugins.facebook
pm $1 com.sonyericsson.socialengine.plugins.picasa
pm $1 com.sonyericsson.socialpane.friends
pm $1 com.sonyericsson.soundlevelalert
pm $1 com.sonyericsson.textinput.chinese
pm $1 com.sonyericsson.textinput.uxp.platform.res.overlay
pm $1 com.sonyericsson.timescape.ui
pm $1 com.sonyericsson.trackid
pm $1 com.sonyericsson.trackid.res.overlay
pm $1 com.sonyericsson.unplugchargerreminder
pm $1 com.sonyericsson.unsupportedheadsetnotifier
pm $1 com.sonyericsson.updatecenter
pm $1 com.sonyericsson.vendor.backuprestore
pm $1 com.sonyericsson.wappush.res.overlay
pm $1 com.sonymobile.advancedwidget.topcontacts
pm $1 com.sonymobile.android.externalkeyboardjp
pm $1 com.sonymobile.androidapp.walkmate
pm $1 com.sonymobile.helpapp7
pm $1 com.sonymobile.runtimeskinning.skin1
pm $1 com.sonymobile.shareapplication
pm $1 com.sonymobile.socialengine.plugins.facebook_sharefrwk
pm $1 com.sonymobile.socialengine.plugins.twitter_sharefrwk
pm $1 com.sonymobile.twitter.account
pm $1 com.sonymobile.twitter.setupwizard
pm $1 com.sonymobile.xperialink
pm $1 com.svox.pico
pm $1 com.trust5.odp
pm $1 com.wsandroid.suite
pm $1 de.arvatomobile.sonyericsson.playnow.android
pm $1 org.microemu.android.se.appello.lp.WisepilotSE
pm $1 com.android.stk
pm $1 com.android.browser
pm $1 com.android.browser.res.overlay
pm $1 com.sonyericsson.advancedwidget.feedwidget
pm $1 com.sonyericsson.advancedwidget.friends
pm $1 com.sonyericsson.tvlauncher
pm $1 com.sonymobile.taskswitcher
pm $1 com.sonyericsson.greentheme
